### ISSUE TITLE
"rbenv global" seems not work on windows 10

### ISSUE THREAD

**Issue by nathanaelyang830427** [nak1114/rbenv-win#10]
I've installed ruby 2.4.3 on windows 10 x64 manually.

Then I found this great tool thus I installed it and run below commands to switch to ruby 2.2.2 for another old project.

However, it seems version switch doesn't work as **ruby -v** always pointing to the manually installed version 2.4.3.

Is anything wrong I've made or would you please have a look?

```bash
Microsoft Windows [Version 10.0.16299.125]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\Nathanael>rbenv versions
* 2.2.2 (set by C:\Users\Nathanael\.rbenv-win\version)

C:\Users\Nathanael>rbenv global 2.2.2

C:\Users\Nathanael>rbenv rehash

C:\Users\Nathanael>ruby -v
ruby 2.4.3p205 (2017-12-14 revision 61247) [x64-mingw32]
```

**Comment by nak1114** [comment]
Please check your env, like below.
````
C:\WINDOWS\system32>echo %PATH%
(....);C:\Users\nak\.rbenv-win\bin;C:\Users\nak\.dcenv\shims;(....)

C:\WINDOWS\system32>
````
In your environment, there is no rbenv path ahead of ruby2.4.3?

The path env searches from the first one, execute the ruby ​​command of 2.4.3 before rbenv.

If this correction is made, ruby2.4.3 can not be executed. 
Because the original has the 'system' keyword, but it doesn't have it.

**Comment by nathanaelyang830427** [comment]
Hi @nak1114 ,

Thank you for your lightning fast response!

I got it. I run to this issue because the system level PATH and user level PATH conflicts when they are merged. I run the commands described in README, however it added path variables to user level, which result in the sequence order in final %PATH% is not as expected and required.

![image](https://user-images.githubusercontent.com/35578759/36122255-b3e4f71e-1016-11e8-8344-0cf0b96840d6.png)

Thus I manually deleted two entries in User Path and add them before ruby 2.4 in System Path. And now it works like a charm!

Thanks man! 🥁🤝

**Comment by nathanaelyang830427** [comment]
Meanwhile, do you think
```bash
for /f "skip=2 delims=" %a in ('reg query HKCU\Environment /v Path') do set orgpath=%a
setx Path "%USERPROFILE%\.rbenv-win\bin;%USERPROFILE%\.rbenv-win\shims;%orgpath:~22%"
```

Can enhance a little bit to ensure it add variables to system level path? If it's necessary, I'd like to open a new enhancement issue for you?
