### ISSUE TITLE
Runtime Error: Type mismatch: 'GetCurrentVersionNoError()

### ISSUE THREAD

**Issue by kirankotari** [nak1114/rbenv-win#15]
I was trying to install rbenv in new system when i tried 
```ruby
rbenv install -l
``` 
I got  `Type mismatch: 'GetCurrentVersionNoError()'` Error. 

[Error @line](https://github.com/nak1114/rbenv-win/blob/23eba595cb83df9ac896c24200429989c43c1284/libexec/rbenv-install.vbs#L439)

I just removed `(0)` from the above line. Can you please validate it, is that correct.

**Comment by nak1114** [comment]
OK, I can reproduce the error.
When no global `version, ` no local `.ruby-version` and no %RBENV_VERSION%, an error occurs.
I'll fix it.
