### ISSUE TITLE
Request: by default calling rbenv rehash after every rbenv install

### ISSUE THREAD

**Issue by kirankotari** [nak1114/rbenv-win#20]
Looks like I need to rbenv rehash after every installation, felt i need to call the rehash command by default after every installation.

**Comment by nak1114** [comment]
Can you solve it by two batches?

Rbenv_install_global.bat
```
rbenv install %1
rbenv global %1
rbenv rehash
```

Rbenv_install_local.bat
```
rbenv install %1
rbenv local %1
rbenv rehash
```

**Comment by kirankotari** [comment]
ignore the pull request. I didn't saw your comment

**Comment by kirankotari** [comment]
I believe `rbenv rehash` is good just after `rbenv install` 
`rbenv local` will automatically set based on .ruby_version file
`rbenv global` it's depends on the user, if he needs he can set else no.

check the pull request, I believe that good.

**Comment by nak1114** [comment]
I finally got it.
Add a feature to switch the environment to the temporarily installed version.
Running the `rehash` command again will return to the current environment.
I also think that this feature is good and merged PR.
