### ISSUE TITLE
Can't find user 22 (ArgumentError) on running `bundle` command

### ISSUE THREAD

**Issue by Vizkrig** [nak1114/rbenv-win#9]
After installing ruby 2.3.1 I installed bundler 1.16.0 and tried a bundle command inside a sample rails app. Here is the error

$ bundle
DL is deprecated, please use Fiddle
The git source `git://github.com/plataformatec/devise.git` uses the `git` protoc
ol, which transmits data without encryption. Disable this warning with `bundle c
onfig git.allow_insecure true`, or switch to the `https` protocol to keep your d
ata secure.
C:/Users/Vishnu/.rbenv-win/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.16.
0/lib/bundler.rb:379:in `expand_path': can't find user 22 (ArgumentError)
        from C:/Users/Vishnu/.rbenv-win/versions/2.1.3/lib/ruby/gems/2.1.0/gems/
bundler-1.16.0/lib/bundler.rb:379:in `block in which'
        from C:/Users/Vishnu/.rbenv-win/versions/2.1.3/lib/ruby/gems/2.1.0/gems/
bundler-1.16.0/lib/bundler.rb:377:in `each'
        from C:/Users/Vishnu/.rbenv-win/versions/2.1.3/lib/ruby/gems/2.1.0/gems/
bundler-1.16.0/lib/bundler.rb:377:in `find'
        from C:/Users/Vishnu/.rbenv-win/versions/2.1.3/lib/ruby/gems/2.1.0/gems/
bundler-1.16.0/lib/bundler.rb:377:in `which'
        from C:/Users/Vishnu/.rbenv-win/versions/2.1.3/lib/ruby/gems/2.1.0/gems/
bundler-1.16.0/lib/bundler.rb:452:in `git_present?'
        from C:/Users/Vishnu/.rbenv-win/versions/2.1.3/lib/ruby/gems/2.1.0/gems/
bundler-1.16.0/lib/bundler/source/git/git_proxy.rb:57:in `initialize'
        from C:/Users/Vishnu/.rbenv-win/versions/2.1.3/lib/ruby/gems/2.1.0/gems/
bundler-1.16.0/lib/bundler/env.rb:84:in `new'
        from C:/Users/Vishnu/.rbenv-win/versions/2.1.3/lib/ruby/gems/2.1.0/gems/
bundler-1.16.0/lib/bundler/env.rb:84:in `git_version'
        from C:/Users/Vishnu/.rbenv-win/versions/2.1.3/lib/ruby/gems/2.1.0/gems/
bundler-1.16.0/lib/bundler/env.rb:119:in `environment'
        from C:/Users/Vishnu/.rbenv-win/versions/2.1.3/lib/ruby/gems/2.1.0/gems/
bundler-1.16.0/lib/bundler/env.rb:17:in `report'
        from C:/Users/Vishnu/.rbenv-win/versions/2.1.3/lib/ruby/gems/2.1.0/gems/
bundler-1.16.0/lib/bundler/friendly_errors.rb:96:in `request_issue_report_for'
        from C:/Users/Vishnu/.rbenv-win/versions/2.1.3/lib/ruby/gems/2.1.0/gems/
bundler-1.16.0/lib/bundler/friendly_errors.rb:46:in `log_error'
        from C:/Users/Vishnu/.rbenv-win/versions/2.1.3/lib/ruby/gems/2.1.0/gems/
bundler-1.16.0/lib/bundler/friendly_errors.rb:126:in `rescue in with_friendly_er
rors'
        from C:/Users/Vishnu/.rbenv-win/versions/2.1.3/lib/ruby/gems/2.1.0/gems/
bundler-1.16.0/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
        from C:/Users/Vishnu/.rbenv-win/versions/2.1.3/lib/ruby/gems/2.1.0/gems/
bundler-1.16.0/exe/bundle:22:in `<top (required)>'
        from C:/Users/Vishnu/.rbenv-win/versions/2.1.3/bin/bundle:23:in `load'
        from C:/Users/Vishnu/.rbenv-win/versions/2.1.3/bin/bundle:23:in `<main>'

Edit: Tried the same with another installation of ruby (2.2.4) and got the same error.

**Comment by nak1114** [comment]
Where is your sample rails app that failed to install?

**Comment by nak1114** [comment]
It didn’t occur in my environment.

```
C:\Users\nak\Documents\repos\rails-test>where ruby
C:\Users\nak\.rbenv-win\shims\ruby.bat

C:\Users\nak\Documents\repos\rails-test>where bundle
C:\Users\nak\.rbenv-win\shims\bundle.bat

C:\Users\nak\Documents\repos\rails-test>ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [i386-mingw32]

C:\Users\nak\Documents\repos\rails-test>bundle -v
Bundler version 1.16.0

C:\Users\nak\Documents\repos\rails-test>type Gemfile
# frozen_string_literal: true
source "http://rubygems.org"

gem 'rails'
gem 'mysql2'
gem 'device'
gem 'mail'
gem 'clockwork'

C:\Users\nak\Documents\repos\rails-test>bundle install --path=vendor/bundle
*snip*
Fetching rails 5.1.4
Installing rails 5.1.4
Bundle complete! 5 Gemfile dependencies, 41 gems now installed.
Bundled gems are installed into `./vendor/bundle`
```

**Comment by Vizkrig** [comment]
> Where is your sample rails app that failed to install?
Its in my desktop

**Comment by Vizkrig** [comment]
So I did a fresh install of rbenv after removing the .rbenv-win folder and clearing all the paths.

I installed bundler by running gem install bundler command.

C:\Users\Vishnu\Desktop\rails_examples\devise_example>gem install bundler
Fetching: bundler-1.16.0.gem (100%)
Successfully installed bundler-1.16.0
Parsing documentation for bundler-1.16.0
Installing ri documentation for bundler-1.16.0
Done installing documentation for bundler after 7 seconds
1 gem installed

C:\Users\Vishnu\Desktop\rails_examples\devise_example>where bundle
INFO: Could not find files for the given pattern(s).

C:\Users\Vishnu\Desktop\rails_examples\devise_example>rbenv rehash

C:\Users\Vishnu\Desktop\rails_examples\devise_example>where bundle
C:\Users\Vishnu\.rbenv-win\shims\bundle.bat

**Comment by nak1114** [comment]
I got it! I found a bug.
There is in [nak1114/install-rbenv-win.bat](https://gist.github.com/nak1114/7ea63204203883c5884d).
Please manually correct the PATH environment variable, below.

```
Path: C:\Users\Vishnu\.rbenv-win\bin;C:\Users\Vishnu\.rbenv-win\shims
```

**Comment by Vizkrig** [comment]
Corrected the path and now it works fine.
